/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GptExplain } from '../models';
// @ts-ignore
import type { TranslateText } from '../models';
/**
 * ReadingApi - axios parameter creator
 * @export
 */
export const ReadingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GptExplain} gptExplain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gptExplain: async (gptExplain: GptExplain, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gptExplain' is not null or undefined
            assertParamExists('gptExplain', 'gptExplain', gptExplain)
            const localVarPath = `/reading/gpt-explain`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(gptExplain, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {TranslateText} translateText 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        translate: async (translateText: TranslateText, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'translateText' is not null or undefined
            assertParamExists('translate', 'translateText', translateText)
            const localVarPath = `/reading/translate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(translateText, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReadingApi - functional programming interface
 * @export
 */
export const ReadingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReadingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {GptExplain} gptExplain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gptExplain(gptExplain: GptExplain, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gptExplain(gptExplain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReadingApi.gptExplain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {TranslateText} translateText 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async translate(translateText: TranslateText, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.translate(translateText, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReadingApi.translate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReadingApi - factory interface
 * @export
 */
export const ReadingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReadingApiFp(configuration)
    return {
        /**
         * 
         * @param {GptExplain} gptExplain 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gptExplain(gptExplain: GptExplain, options?: any): AxiosPromise<string> {
            return localVarFp.gptExplain(gptExplain, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TranslateText} translateText 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        translate(translateText: TranslateText, options?: any): AxiosPromise<string> {
            return localVarFp.translate(translateText, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReadingApi - object-oriented interface
 * @export
 * @class ReadingApi
 * @extends {BaseAPI}
 */
export class ReadingApi extends BaseAPI {
    /**
     * 
     * @param {GptExplain} gptExplain 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReadingApi
     */
    public gptExplain(gptExplain: GptExplain, options?: RawAxiosRequestConfig) {
        return ReadingApiFp(this.configuration).gptExplain(gptExplain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TranslateText} translateText 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReadingApi
     */
    public translate(translateText: TranslateText, options?: RawAxiosRequestConfig) {
        return ReadingApiFp(this.configuration).translate(translateText, options).then((request) => request(this.axios, this.basePath));
    }
}

