/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateImpressionDto
 */
export interface CreateImpressionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateImpressionDto
     */
    'text'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateImpressionDto
     */
    'rating': number;
    /**
     * 
     * @type {string}
     * @memberof CreateImpressionDto
     */
    'bookId': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateImpressionDto
     */
    'tags'?: Array<string>;
}

