/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FeaturedOutputBooksBySelectedGenresInner } from './featured-output-books-by-selected-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FeaturedOutputGenresInner } from './featured-output-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInner } from './sync-library-response-reading-books-inner';

/**
 * 
 * @export
 * @interface FeaturedOutput
 */
export interface FeaturedOutput {
    /**
     * 
     * @type {Array<SyncLibraryResponseReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'picksOfWeek': Array<SyncLibraryResponseReadingBooksInner>;
    /**
     * 
     * @type {Array<FeaturedOutputGenresInner>}
     * @memberof FeaturedOutput
     */
    'genres': Array<FeaturedOutputGenresInner>;
    /**
     * 
     * @type {Array<SyncLibraryResponseReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'bestSellingBooks': Array<SyncLibraryResponseReadingBooksInner>;
    /**
     * 
     * @type {Array<FeaturedOutputBooksBySelectedGenresInner>}
     * @memberof FeaturedOutput
     */
    'booksBySelectedGenres': Array<FeaturedOutputBooksBySelectedGenresInner>;
}

