/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInner } from './sync-library-response-reading-books-inner';

/**
 * 
 * @export
 * @interface FeaturedOutputBooksBySelectedGenresInner
 */
export interface FeaturedOutputBooksBySelectedGenresInner {
    /**
     * 
     * @type {string}
     * @memberof FeaturedOutputBooksBySelectedGenresInner
     */
    'name': string;
    /**
     * 
     * @type {Array<SyncLibraryResponseReadingBooksInner>}
     * @memberof FeaturedOutputBooksBySelectedGenresInner
     */
    'books': Array<SyncLibraryResponseReadingBooksInner>;
}

