/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeaturedOutputGenresInner
 */
export interface FeaturedOutputGenresInner {
    /**
     * 
     * @type {string}
     * @memberof FeaturedOutputGenresInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FeaturedOutputGenresInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FeaturedOutputGenresInner
     */
    'icon': string;
    /**
     * 
     * @type {string}
     * @memberof FeaturedOutputGenresInner
     */
    'emoji': string;
}

