/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FullBookCount
 */
export interface FullBookCount {
    /**
     * 
     * @type {number}
     * @memberof FullBookCount
     */
    'finishedBy'?: number;
    /**
     * 
     * @type {number}
     * @memberof FullBookCount
     */
    'readingBy'?: number;
    /**
     * 
     * @type {number}
     * @memberof FullBookCount
     */
    'savedBy'?: number;
}

