/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FeaturedOutputGenresInner } from './featured-output-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FullBookCount } from './full-book-count';
// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInnerAuthor } from './sync-library-response-reading-books-inner-author';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCatalogOutputDataInnerStatisticsInner } from './user-catalog-output-data-inner-statistics-inner';

/**
 * 
 * @export
 * @interface FullBook
 */
export interface FullBook {
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof FullBook
     */
    'rating': number;
    /**
     * 
     * @type {boolean}
     * @memberof FullBook
     */
    'isPublic': boolean;
    /**
     * 
     * @type {Array<FeaturedOutputGenresInner>}
     * @memberof FullBook
     */
    'genres': Array<FeaturedOutputGenresInner>;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'picture': string;
    /**
     * 
     * @type {SyncLibraryResponseReadingBooksInnerAuthor}
     * @memberof FullBook
     */
    'author': SyncLibraryResponseReadingBooksInnerAuthor;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'authorId': string;
    /**
     * 
     * @type {boolean}
     * @memberof FullBook
     */
    'isRecommendable': boolean;
    /**
     * 
     * @type {FullBookCount}
     * @memberof FullBook
     */
    '_count': FullBookCount;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerStatisticsInner>}
     * @memberof FullBook
     */
    'statistics': Array<UserCatalogOutputDataInnerStatisticsInner>;
}

