/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GptExplain
 */
export interface GptExplain {
    /**
     * 
     * @type {string}
     * @memberof GptExplain
     */
    'selectedText': string;
    /**
     * 
     * @type {string}
     * @memberof GptExplain
     */
    'bookTitle': string;
    /**
     * 
     * @type {string}
     * @memberof GptExplain
     */
    'targetLang': string;
    /**
     * 
     * @type {string}
     * @memberof GptExplain
     */
    'context': string;
    /**
     * 
     * @type {string}
     * @memberof GptExplain
     */
    'bookAuthor': string;
}

