/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInnerAuthor } from './sync-library-response-reading-books-inner-author';

/**
 * 
 * @export
 * @interface ReactionOutputBook
 */
export interface ReactionOutputBook {
    /**
     * 
     * @type {string}
     * @memberof ReactionOutputBook
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutputBook
     */
    'title'?: string;
    /**
     * 
     * @type {SyncLibraryResponseReadingBooksInnerAuthor}
     * @memberof ReactionOutputBook
     */
    'author'?: SyncLibraryResponseReadingBooksInnerAuthor;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutputBook
     */
    'picture'?: string;
}

