/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReactionOutputBook } from './reaction-output-book';

/**
 * 
 * @export
 * @interface ReactionOutput
 */
export interface ReactionOutput {
    /**
     * 
     * @type {string}
     * @memberof ReactionOutput
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutput
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutput
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutput
     */
    'xpath': string;
    /**
     * 
     * @type {number}
     * @memberof ReactionOutput
     */
    'startOffset': number;
    /**
     * 
     * @type {number}
     * @memberof ReactionOutput
     */
    'endOffset': number;
    /**
     * 
     * @type {ReactionOutputBook}
     * @memberof ReactionOutput
     */
    'book': ReactionOutputBook;
}

