/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReactionPayloadCreateInner
 */
export interface ReactionPayloadCreateInner {
    /**
     * 
     * @type {string}
     * @memberof ReactionPayloadCreateInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionPayloadCreateInner
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionPayloadCreateInner
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionPayloadCreateInner
     */
    'xpath': string;
    /**
     * 
     * @type {number}
     * @memberof ReactionPayloadCreateInner
     */
    'startOffset': number;
    /**
     * 
     * @type {number}
     * @memberof ReactionPayloadCreateInner
     */
    'endOffset': number;
    /**
     * 
     * @type {string}
     * @memberof ReactionPayloadCreateInner
     */
    'bookId': string;
}

