/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReadingHistory
 */
export interface ReadingHistory {
    /**
     * 
     * @type {string}
     * @memberof ReadingHistory
     */
    'startDate': string;
    /**
     * 
     * @type {string}
     * @memberof ReadingHistory
     */
    'endDate': string;
    /**
     * 
     * @type {number}
     * @memberof ReadingHistory
     */
    'startProgress': number;
    /**
     * 
     * @type {string}
     * @memberof ReadingHistory
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof ReadingHistory
     */
    'endProgress': number;
    /**
     * 
     * @type {number}
     * @memberof ReadingHistory
     */
    'progressDelta': number;
    /**
     * 
     * @type {number}
     * @memberof ReadingHistory
     */
    'readingTimeMs': number;
    /**
     * 
     * @type {number}
     * @memberof ReadingHistory
     */
    'scrollPosition': number;
    /**
     * 
     * @type {string}
     * @memberof ReadingHistory
     */
    'bookId': string;
}

