/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SyncLibraryPayload
 */
export interface SyncLibraryPayload {
    /**
     * 
     * @type {string}
     * @memberof SyncLibraryPayload
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SyncLibraryPayload
     */
    'status': StatusEnum;
}

export const StatusEnum = {
    Reading: 'reading',
    Finished: 'finished',
    Saved: 'saved',
    Deleted: 'deleted'
} as const;

export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


