/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateChapterDto
 */
export interface UpdateChapterDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateChapterDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateChapterDto
     */
    'content'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateChapterDto
     */
    'position'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateChapterDto
     */
    'wordCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateChapterDto
     */
    'symbolCount'?: number;
}

