/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserStatisticsOutputStatisticsInner } from './user-statistics-output-statistics-inner';

/**
 * 
 * @export
 * @interface UserStatisticsOutput
 */
export interface UserStatisticsOutput {
    /**
     * 
     * @type {string}
     * @memberof UserStatisticsOutput
     */
    'joinedTime': string;
    /**
     * 
     * @type {Array<UserStatisticsOutputStatisticsInner>}
     * @memberof UserStatisticsOutput
     */
    'statistics': Array<UserStatisticsOutputStatisticsInner>;
}

