/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserCatalogOutputDataInnerCount
 */
export interface UserCatalogOutputDataInnerCount {
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutputDataInnerCount
     */
    'savedBooks'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutputDataInnerCount
     */
    'finishedBooks'?: number;
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutputDataInnerCount
     */
    'readingBooks'?: number;
}

