/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './clients/admin-author-api';
export * from './clients/admin-book-api';
export * from './clients/admin-ebook-api';
export * from './clients/admin-user-api';
export * from './clients/auth-api';
export * from './clients/author-api';
export * from './clients/book-api';
export * from './clients/catalog-api';
export * from './clients/ebook-api';
export * from './clients/genre-api';
export * from './clients/health-api';
export * from './clients/reading-api';
export * from './clients/recommendation-api';
export * from './clients/storage-api';
export * from './clients/user-api';

