/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Check503ResponseInfoValue } from './check503-response-info-value';

/**
 * 
 * @export
 * @interface Check503Response
 */
export interface Check503Response {
    /**
     * 
     * @type {string}
     * @memberof Check503Response
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: Check503ResponseInfoValue; }}
     * @memberof Check503Response
     */
    'info'?: { [key: string]: Check503ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: Check503ResponseInfoValue; }}
     * @memberof Check503Response
     */
    'error'?: { [key: string]: Check503ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: Check503ResponseInfoValue; }}
     * @memberof Check503Response
     */
    'details'?: { [key: string]: Check503ResponseInfoValue; };
}

