/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateAuthorDto
 */
export interface CreateAuthorDto {
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorDto
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorDto
     */
    'dateOfBirth': string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorDto
     */
    'dateOfDeath': string | null;
}

