/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBookDtoChaptersInner } from './create-book-dto-chapters-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FeaturedOutputGenresInner } from './featured-output-genres-inner';

/**
 * 
 * @export
 * @interface CreateBookDto
 */
export interface CreateBookDto {
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'age': AgeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'authorId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof CreateBookDto
     */
    'rating': number;
    /**
     * 
     * @type {Array<CreateBookDtoChaptersInner>}
     * @memberof CreateBookDto
     */
    'chapters': Array<CreateBookDtoChaptersInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'picture': string;
    /**
     * 
     * @type {Array<FeaturedOutputGenresInner>}
     * @memberof CreateBookDto
     */
    'genres': Array<FeaturedOutputGenresInner>;
}

export const AgeEnum = {
    All: 'all',
    Kids: 'kids',
    Teens: 'teens',
    Adults: 'adults'
} as const;

export type AgeEnum = typeof AgeEnum[keyof typeof AgeEnum];


