/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EbookOutputChaptersInner } from './ebook-output-chapters-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { EbookOutputFunctionEnums } from './ebook-output-function-enums';
// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInnerAuthor } from './sync-library-response-reading-books-inner-author';

/**
 * 
 * @export
 * @interface EbookOutput
 */
export interface EbookOutput {
    /**
     * 
     * @type {Array<EbookOutputChaptersInner>}
     * @memberof EbookOutput
     */
    'chapters': Array<EbookOutputChaptersInner>;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'file': string;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'onLoadScript': string;
    /**
     * 
     * @type {EbookOutputFunctionEnums}
     * @memberof EbookOutput
     */
    'functionEnums': EbookOutputFunctionEnums;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'picture': string;
    /**
     * 
     * @type {SyncLibraryResponseReadingBooksInnerAuthor}
     * @memberof EbookOutput
     */
    'author': SyncLibraryResponseReadingBooksInnerAuthor;
}

