/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FeaturedOutputGenresInner } from './featured-output-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInner } from './sync-library-response-reading-books-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInnerAuthor } from './sync-library-response-reading-books-inner-author';

/**
 * 
 * @export
 * @interface InfoById
 */
export interface InfoById {
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'language': string;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof InfoById
     */
    'rating': number;
    /**
     * 
     * @type {boolean}
     * @memberof InfoById
     */
    'isPublic': boolean;
    /**
     * 
     * @type {Array<FeaturedOutputGenresInner>}
     * @memberof InfoById
     */
    'genres': Array<FeaturedOutputGenresInner>;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'picture': string;
    /**
     * 
     * @type {SyncLibraryResponseReadingBooksInnerAuthor}
     * @memberof InfoById
     */
    'author': SyncLibraryResponseReadingBooksInnerAuthor;
    /**
     * 
     * @type {string}
     * @memberof InfoById
     */
    'readingTime': string;
    /**
     * 
     * @type {Array<SyncLibraryResponseReadingBooksInner>}
     * @memberof InfoById
     */
    'fromSameAuthor': Array<SyncLibraryResponseReadingBooksInner>;
}

