/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReactionPayloadCreateInner } from './reaction-payload-create-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ReactionPayloadUpdateInner } from './reaction-payload-update-inner';

/**
 * 
 * @export
 * @interface ReactionPayload
 */
export interface ReactionPayload {
    /**
     * 
     * @type {Array<ReactionPayloadCreateInner>}
     * @memberof ReactionPayload
     */
    'create': Array<ReactionPayloadCreateInner>;
    /**
     * 
     * @type {Array<ReactionPayloadUpdateInner>}
     * @memberof ReactionPayload
     */
    'update': Array<ReactionPayloadUpdateInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReactionPayload
     */
    'delete': Array<string>;
}

