/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SyncLibraryResponseReadingBooksInnerAuthor } from './sync-library-response-reading-books-inner-author';

/**
 * 
 * @export
 * @interface SyncLibraryResponseReadingBooksInner
 */
export interface SyncLibraryResponseReadingBooksInner {
    /**
     * 
     * @type {string}
     * @memberof SyncLibraryResponseReadingBooksInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SyncLibraryResponseReadingBooksInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SyncLibraryResponseReadingBooksInner
     */
    'picture': string;
    /**
     * 
     * @type {SyncLibraryResponseReadingBooksInnerAuthor}
     * @memberof SyncLibraryResponseReadingBooksInner
     */
    'author': SyncLibraryResponseReadingBooksInnerAuthor;
    /**
     * 
     * @type {number}
     * @memberof SyncLibraryResponseReadingBooksInner
     */
    'rating': number;
}

