/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnfoldOutputChaptersInner
 */
export interface UnfoldOutputChaptersInner {
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputChaptersInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputChaptersInner
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputChaptersInner
     */
    'id': string;
}

