/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserCatalogOutputDataInner } from './user-catalog-output-data-inner';

/**
 * 
 * @export
 * @interface UserCatalogOutput
 */
export interface UserCatalogOutput {
    /**
     * 
     * @type {Array<UserCatalogOutputDataInner>}
     * @memberof UserCatalogOutput
     */
    'data': Array<UserCatalogOutputDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof UserCatalogOutput
     */
    'canLoadMore': boolean;
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutput
     */
    'totalPages': number;
}

