/* tslint:disable */
/* eslint-disable */
/**
 * booknest
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ReactionOutput } from '../models';
// @ts-ignore
import type { ReactionPayload } from '../models';
// @ts-ignore
import type { ReadingHistory } from '../models';
// @ts-ignore
import type { SyncLibraryPayload } from '../models';
// @ts-ignore
import type { SyncLibraryResponse } from '../models';
// @ts-ignore
import type { UserStatistics } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<ReadingHistory>} readingHistory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncHistory: async (readingHistory: Array<ReadingHistory>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'readingHistory' is not null or undefined
            assertParamExists('syncHistory', 'readingHistory', readingHistory)
            const localVarPath = `/user/sync-history`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(readingHistory, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<SyncLibraryPayload>} syncLibraryPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncLibrary: async (syncLibraryPayload: Array<SyncLibraryPayload>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'syncLibraryPayload' is not null or undefined
            assertParamExists('syncLibrary', 'syncLibraryPayload', syncLibraryPayload)
            const localVarPath = `/user/sync-library`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(syncLibraryPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ReactionPayload} reactionPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncReaction: async (reactionPayload: ReactionPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reactionPayload' is not null or undefined
            assertParamExists('syncReaction', 'reactionPayload', reactionPayload)
            const localVarPath = `/user/sync-reaction`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reactionPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserStatistics>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statistics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.statistics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<ReadingHistory>} readingHistory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncHistory(readingHistory: Array<ReadingHistory>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReadingHistory>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncHistory(readingHistory, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.syncHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<SyncLibraryPayload>} syncLibraryPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncLibrary(syncLibraryPayload: Array<SyncLibraryPayload>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SyncLibraryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncLibrary(syncLibraryPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.syncLibrary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ReactionPayload} reactionPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async syncReaction(reactionPayload: ReactionPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ReactionOutput>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.syncReaction(reactionPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.syncReaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statistics(options?: any): AxiosPromise<Array<UserStatistics>> {
            return localVarFp.statistics(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<ReadingHistory>} readingHistory 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncHistory(readingHistory: Array<ReadingHistory>, options?: any): AxiosPromise<Array<ReadingHistory>> {
            return localVarFp.syncHistory(readingHistory, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<SyncLibraryPayload>} syncLibraryPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncLibrary(syncLibraryPayload: Array<SyncLibraryPayload>, options?: any): AxiosPromise<SyncLibraryResponse> {
            return localVarFp.syncLibrary(syncLibraryPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ReactionPayload} reactionPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        syncReaction(reactionPayload: ReactionPayload, options?: any): AxiosPromise<Array<ReactionOutput>> {
            return localVarFp.syncReaction(reactionPayload, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public statistics(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).statistics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<ReadingHistory>} readingHistory 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public syncHistory(readingHistory: Array<ReadingHistory>, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).syncHistory(readingHistory, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<SyncLibraryPayload>} syncLibraryPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public syncLibrary(syncLibraryPayload: Array<SyncLibraryPayload>, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).syncLibrary(syncLibraryPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ReactionPayload} reactionPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public syncReaction(reactionPayload: ReactionPayload, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).syncReaction(reactionPayload, options).then((request) => request(this.axios, this.basePath));
    }
}

